-- Fix investment ranges to match database constraints
-- Valid values: '$1K-$10K', '$10K-$50K', '$50K-$100K', '$100K-$500K', '$500K-$1M', '$1M-$5M', '$5M+'

INSERT INTO profiles (
  full_name, email, headshot_url, location, linkedin_profile, website_portfolio, 
  short_bio, availability, looking_for, role, investment_range, investment_stage, 
  investment_focus, portfolio_companies, investment_criteria, approved, featured, created_at
) VALUES 
('83North (Greylock IL)', 'contact@83north.com', 'https://media.licdn.com/dms/image/v2/C4E0BAQHM4yn93Q6-Uw/company-logo_200_200/company-logo_200_200/0/1630566660145/83north_logo?e=1762992000&v=beta&t=YLrYKP4srsC28FOsDCBYbJlIYHwgGePBUvmEsScWP0Y', 'Israel/UK', 'https://linkedin.com/company/83north', NULL, 'Leading venture capital firm with flagship investments in IronSource and Mirakl. Focus on growth-stage technology companies.', 'Full-time', 'Growth-stage startups', 'investor', '$1M-$5M', 'Series A', 'Technology, SaaS', 'IronSource, Mirakl', 'Strong team, proven traction, scalable business model', true, true, NOW()),

('A16Z Speedrun', 'speedrun@a16z.com', 'https://media.licdn.com/dms/image/v2/D560BAQFs3wvS2NM10g/company-logo_200_200/B56ZaiHxu.GoAU-/0/1746476670161/a16z_logo?e=1762992000&v=beta&t=Ive3g1DDYGHv7N7UAZuy6uTJmMGzitc5_rLdHeoPjaM', 'USA', 'https://linkedin.com/company/andreessen-horowitz', NULL, 'Andreessen Horowitz speedrun program for early-stage startups. Portfolio includes k‑ID and Hedra.', 'Full-time', 'Early-stage startups', 'investor', '$500K-$1M', 'Seed', 'AI, Consumer Tech', 'k‑ID, Hedra', 'Innovative technology, strong founding team, clear market opportunity', true, true, NOW()),

('NTX', 'contact@ntx.com', 'https://media.licdn.com/dms/image/v2/D4E0BAQGXMcX-xiIrGQ/company-logo_200_200/company-logo_200_200/0/1737994150598/ntx_it_logo?e=1762992000&v=beta&t=6MSR6iQDItarzwzGPqGekVOUEMTk9_8SD26kge7KUFs', 'USA', 'https://linkedin.com/company/accel', NULL, 'Technology-focused venture capital with successful investments in Slack and Atlassian.', 'Full-time', 'Enterprise software startups', 'investor', '$5M+', 'Series A', 'Enterprise Software, SaaS', 'Slack, Atlassian', 'Enterprise-ready solutions, strong product-market fit, experienced team', true, false, NOW()),

('AI Fund', 'contact@aifund.ai', 'https://media.licdn.com/dms/image/v2/C4D0BAQFf9dbpZcfsRQ/company-logo_200_200/company-logo_200_200/0/1631781397052/ai_fund_logo?e=1762992000&v=beta&t=rIf9EjbtS9n9V8NuB9hGvLFMRXtEZ4sLaNm1ZmCSEck', 'USA', 'https://linkedin.com/company/ai-fund', NULL, 'Specialized AI-focused venture fund with investments in Gaia Dynamics and SkyFire AI.', 'Full-time', 'AI/ML startups', 'investor', '$100K-$500K', 'Angel', 'Artificial Intelligence, Machine Learning', 'Gaia Dynamics, SkyFire AI', 'AI-first approach, technical excellence, scalable AI solutions', true, false, NOW()),

('Andreessen Horowitz', 'contact@a16z.com', 'https://media.licdn.com/dms/image/v2/D560BAQFs3wvS2NM10g/company-logo_200_200/B56ZaiHxu.GoAU-/0/1746476670161/a16z_logo?e=1762992000&v=beta&t=Ive3g1DDYGHv7N7UAZuy6uTJmMGzitc5_rLdHeoPjaM', 'USA', 'https://linkedin.com/company/andreessen-horowitz', NULL, 'Premier Silicon Valley VC firm with legendary investments in GitHub and Airbnb. Leading technology investor.', 'Full-time', 'Technology startups', 'investor', '$5M+', 'Series B+', 'Technology, Software, Crypto', 'GitHub, Airbnb', 'Exceptional founders, large market opportunity, disruptive technology', true, true, NOW()),

('Y Combinator', 'contact@ycombinator.com', 'https://media.licdn.com/dms/image/v2/C4D0BAQGPzdBPNxrmEg/company-logo_200_200/company-logo_200_200/0/1673555093250/y_combinator_logo?e=1762992000&v=beta&t=5hHJwShvaLj3qZj_jWWatMYC5zC5WC6jvp-GEBsZFxw', 'USA', 'https://linkedin.com/company/y-combinator', NULL, 'World''s most successful startup accelerator with alumni including Dropbox and Airbnb. The gold standard for early-stage funding.', 'Full-time', 'Early-stage startups', 'investor', '$100K-$500K', 'Angel', 'All sectors', 'Dropbox, Airbnb', 'Strong founding team, clear vision, ability to execute quickly', true, true, NOW());